# Generated by Django 2.1.4 on 2019-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(db_index=True, max_length=30)),
                ('last_name', models.CharField(db_index=True, max_length=30)),
                ('emp_id', models.CharField(db_index=True, max_length=9, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('active_status', models.BooleanField(db_index=True)),
                ('phone_num', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(db_index=True, max_length=30)),
                ('job_name', models.CharField(db_index=True, max_length=30)),
                ('units_equal', models.IntegerField(db_index=True)),
                ('num_steps', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
