# Generated by Django 2.1.4 on 2019-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(db_index=True, max_length=30)),
                ('last_name', models.CharField(db_index=True, max_length=30)),
                ('emp_id', models.CharField(db_index=True, max_length=9, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('active_status', models.BooleanField(db_index=True)),
                ('phone_num', models.CharField(db_index=True, max_length=15)),
            ],
        ),
    ]
