# Generated by Django 2.1.7 on 2019-04-20 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=30)),
                ('last_name', models.CharField(db_index=True, max_length=30)),
                ('address', models.CharField(blank=True, db_index=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('active_status', models.BooleanField(db_index=True, default=True)),
                ('phone_num', models.CharField(blank=True, db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date_completed', models.DateField(db_index=True, default=datetime.date.today)),
                ('job_name', models.CharField(db_index=True, max_length=30)),
                ('piece_rate', models.DecimalField(db_index=True, decimal_places=4, max_digits=5)),
                ('hours', models.IntegerField(db_index=True, null=True)),
                ('units_produced', models.IntegerField(db_index=True, null=True)),
                ('absent', models.IntegerField(db_index=True)),
                ('employee_name', models.ForeignKey(limit_choices_to=models.Q(active_status=True), on_delete=django.db.models.deletion.CASCADE, to='webapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('standard_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('job_name', models.CharField(db_index=True, max_length=30)),
                ('units_equal', models.IntegerField(db_index=True)),
                ('num_steps', models.IntegerField(db_index=True)),
                ('job_description', models.CharField(db_index=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'standard',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.CharField(db_index=True, max_length=2, primary_key=True, serialize=False)),
                ('units_hr', models.IntegerField(db_index=True)),
                ('time_each', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('piece_rate', models.DecimalField(db_index=True, decimal_places=4, max_digits=5)),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Standard')),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='standard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Standard'),
        ),
        migrations.AddField(
            model_name='report',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Step'),
        ),
    ]
