# Generated by Django 2.1.4 on 2019-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_id', models.CharField(db_index=True, max_length=30)),
                ('job_name', models.CharField(db_index=True, max_length=30)),
                ('units_equal', models.IntegerField(db_index=True)),
                ('num_steps', models.IntegerField(db_index=True)),
            ],
        ),

    ]
