# Generated by Django 2.1.4 on 2019-02-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190205_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
