# Generated by Django 2.1.4 on 2019-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190206_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='company_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='job_description',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='step_id',
            field=models.CharField(db_index=True, max_length=3, null=True),
        ),
        migrations.AlterModelTable(
            name='standard',
            table='standard',
        ),
    ]
