# Generated by Django 2.1.4 on 2019-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190206_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(db_index=True, max_length=3, null=True)),
                ('standard_id', models.CharField(db_index=True, max_length=30)),
                ('job_name', models.CharField(db_index=True, max_length=30)),
                ('employee_name', models.CharField(db_index=True, max_length=40)),
                ('piece_rate', models.IntegerField(db_index=True, null=True)),
                ('hours', models.IntegerField(db_index=True, null=True)),
                ('units_produced', models.IntegerField(db_index=True, null=True)),
                ('absent', models.IntegerField(db_index=True)),
            ],
        ),
    ]
